TrailingWhitespace:
  Enabled: false

LineLength:
  Enabled: false

StringLiterals:
  Enabled: false

EmptyLines:
  Enabled: false

AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/schema.rb
    - db/migrate/**
    - bin/**
    - config/**
    - script/**